# Clase 07 — Python + SQL

> Notebook de práctica. Ejecutá las celdas a medida que avanzás en el artículo.

### El dataset de esta clase
 
Para estos ejercicios vas a trabajar con una base de datos de una clínica veterinaria llamada **VetCare**. Tiene tres tablas relacionadas: dueños, mascotas y consultas médicas.
 
Antes de hacer cualquier ejercicio, ejecutá este script una sola vez para crear y poblar la base de datos:

In [1]:
import sqlite3
 
conexion = sqlite3.connect("vetcare.db")
cursor = conexion.cursor()
 
cursor.executescript("""
    CREATE TABLE IF NOT EXISTS duenos (
        id          INTEGER PRIMARY KEY,
        nombre      TEXT,
        ciudad      TEXT,
        telefono    TEXT
    );
 
    CREATE TABLE IF NOT EXISTS mascotas (
        id          INTEGER PRIMARY KEY,
        nombre      TEXT,
        especie     TEXT,
        raza        TEXT,
        edad        INTEGER,
        dueno_id    INTEGER,
        FOREIGN KEY (dueno_id) REFERENCES duenos(id)
    );
 
    CREATE TABLE IF NOT EXISTS consultas (
        id              INTEGER PRIMARY KEY,
        mascota_id      INTEGER,
        fecha           TEXT,
        motivo          TEXT,
        costo           REAL,
        veterinario     TEXT,
        FOREIGN KEY (mascota_id) REFERENCES mascotas(id)
    );
 
    INSERT INTO duenos (nombre, ciudad, telefono) VALUES
        ('Ana Torres',    'Buenos Aires', '11-4421-3390'),
        ('Luis Gómez',    'Córdoba',      '351-882-4411'),
        ('Clara Díaz',    'Rosario',      '341-553-7762'),
        ('Pedro Ruiz',    'Buenos Aires', '11-6634-8821'),
        ('María López',   'Mendoza',      '261-445-9900');
 
    INSERT INTO mascotas (nombre, especie, raza, edad, dueno_id) VALUES
        ('Toby',    'perro',  'Labrador',         4,  1),
        ('Mishi',   'gato',   'Siamés',           2,  1),
        ('Rocky',   'perro',  'Pastor Alemán',    7,  2),
        ('Luna',    'gato',   'Persa',            1,  3),
        ('Max',     'perro',  'Golden Retriever', 5,  3),
        ('Coco',    'loro',   'Cacatúa',          3,  4),
        ('Nala',    'perro',  'Beagle',           6,  4),
        ('Simba',   'gato',   'Común Europeo',    9,  5),
        ('Bono',    'perro',  'Bulldog',          2,  5),
        ('Kira',    'gato',   'Angora',           4,  2);
 
    INSERT INTO consultas (mascota_id, fecha, motivo, costo, veterinario) VALUES
        (1,  '2024-03-01', 'vacunación',         3500.0,  'Dra. Sosa'),
        (1,  '2024-06-15', 'control anual',      4200.0,  'Dr. Vera'),
        (2,  '2024-01-20', 'esterilización',     18000.0, 'Dra. Sosa'),
        (3,  '2024-02-10', 'cirugía rodilla',    45000.0, 'Dr. Vera'),
        (3,  '2024-02-25', 'control post-op',    3800.0,  'Dr. Vera'),
        (4,  '2024-04-05', 'vacunación',         3200.0,  'Dra. Sosa'),
        (5,  '2024-03-18', 'control anual',      4200.0,  'Dra. Romero'),
        (5,  '2024-05-22', 'desparasitación',    2800.0,  'Dra. Romero'),
        (6,  '2024-01-08', 'chequeo general',    5500.0,  'Dr. Vera'),
        (7,  '2024-04-30', 'control anual',      4200.0,  'Dra. Sosa'),
        (7,  '2024-07-14', 'vacunación',         3500.0,  'Dra. Sosa'),
        (8,  '2024-02-28', 'chequeo general',    4200.0,  'Dra. Romero'),
        (9,  '2024-05-10', 'vacunación',         3500.0,  'Dr. Vera'),
        (9,  '2024-06-01', 'control anual',      4200.0,  'Dr. Vera'),
        (10, '2024-03-25', 'esterilización',     15000.0, 'Dra. Sosa');
""")
 
conexion.commit()
conexion.close()
print("Base de datos vetcare.db creada correctamente.")

Base de datos vetcare.db creada correctamente.

### Ejercicio 1 — ¿Qué hay adentro?
 
Te acaban de dar acceso a la base de datos `vetcare.db` de un proyecto nuevo. No sabés qué tablas tiene ni cómo están estructuradas. Antes de escribir cualquier consulta, necesitás entender qué tiene adentro.
 
**Consigna:** Sin mirar el script de creación de arriba, conectate a `vetcare.db` y respondé estas preguntas usando solo Python:
 
1. ¿Qué tablas tiene la base de datos?
2. ¿Qué columnas tiene cada tabla y de qué tipo son?

In [2]:
import sqlite3
import pandas as pd
 
conexion = sqlite3.connect("vetcare.db")
tablas = pd.read_sql(
    "SELECT name FROM sqlite_master WHERE type='table'",
    conexion
)

print(tablas)
 
# Tu tarea: usar sqlite_master y PRAGMA table_info() para explorar la DB
# sin asumir nada de antemano sobre su estructura

        name
0     duenos
1   mascotas
2  consultas

In [4]:
estructura = pd.read_sql(
    "PRAGMA table_info(duenos)",
    conexion
)
print(estructura)
print("-------- ")

estructura2 = pd.read_sql(
    "PRAGMA table_info(mascotas)",
    conexion
)
print(estructura2)
print("-------- ")

estructura3 = pd.read_sql(
    "PRAGMA table_info(consultas)",
    conexion
)
print(estructura3)

   cid      name     type  notnull dflt_value  pk
0    0        id  INTEGER        0       None   1
1    1    nombre     TEXT        0       None   0
2    2    ciudad     TEXT        0       None   0
3    3  telefono     TEXT        0       None   0
--------
   cid      name     type  notnull dflt_value  pk
0    0        id  INTEGER        0       None   1
1    1    nombre     TEXT        0       None   0
2    2   especie     TEXT        0       None   0
3    3      raza     TEXT        0       None   0
4    4      edad  INTEGER        0       None   0
5    5  dueno_id  INTEGER        0       None   0
--------
   cid         name     type  notnull dflt_value  pk
0    0           id  INTEGER        0       None   1
1    1   mascota_id  INTEGER        0       None   0
2    2        fecha     TEXT        0       None   0
3    3       motivo     TEXT        0       None   0
4    4        costo     REAL        0       None   0
5    5  veterinario     TEXT        0       None   0

> **Por qué importa esto:** en un proyecto real nunca vas a tener el script de creación a mano. Saber cómo explorar una base de datos desconocida es la primera habilidad que necesitás antes de poder analizarla.

### Ejercicio 2 — Investigación: ¿cuántas filas tiene cada tabla?
 
Después de explorar la estructura, la segunda pregunta siempre es cuántos registros tiene cada tabla. Esto no lo viste en el artículo — tenés que investigarlo.
 
**Consigna:** Investiga la función `COUNT(*)` en SQL y usala para averiguar cuántas filas tiene cada una de las tres tablas. Hacé una consulta separada por tabla y mostrá los resultados.

In [6]:
import sqlite3
import pandas as pd
 
conexion = sqlite3.connect("vetcare.db")
cantidad_registros = pd.read_sql(
    "SELECT COUNT(*) FROM duenos",
    conexion
)

print(cantidad_registros)

cantidad_registros2 = pd.read_sql(
    "SELECT COUNT(*) FROM mascotas",
    conexion
)

print(cantidad_registros2)

cantidad_registros3 = pd.read_sql(
    "SELECT COUNT(*) FROM consultas",
    conexion
)

print(cantidad_registros3)

 
# Tu tarea: averiguar cuántas filas tiene cada tabla usando COUNT(*)

   COUNT(*)
0         5
   COUNT(*)
0        10
   COUNT(*)
0        15

> **Para pensar:** ¿por qué `COUNT(*)` en lugar de simplemente `len(df)` después de traer todo con `pd.read_sql()`? ¿Cuándo importaría esa diferencia?

### Ejercicio 3 — Tu primera consulta desde Python
 
Ya sabés escribir SQL en SQLBolt. Ahora el objetivo es hacer exactamente lo mismo, pero desde Python, y recibir el resultado como un DataFrame.
 
**Consigna:** Usando `pd.read_sql()`, traé todas las mascotas de la tabla `mascotas` y guardá el resultado en un DataFrame llamado `df_mascotas`. Después respondé usando solo operaciones de Pandas que ya conocés:
 
1. ¿Cuántas mascotas hay en total?
2. ¿Cuáles son los nombres de las columnas?
3. Mostrá solo las primeras 3 filas.

In [17]:
import sqlite3
import pandas as pd
 
conexion = sqlite3.connect("vetcare.db")
 
df_mascotas = pd.read_sql("SELECT * FROM mascotas", conexion)

#print(len(df_mascotas))
#print(df_mascotas.columns)
#print(df_mascotas.head(3))
df_mascotas.info

<bound method DataFrame.info of    id nombre especie              raza  edad  dueno_id
0   1   Toby   perro          Labrador     4         1
1   2  Mishi    gato            Siamés     2         1
2   3  Rocky   perro     Pastor Alemán     7         2
3   4   Luna    gato             Persa     1         3
4   5    Max   perro  Golden Retriever     5         3
5   6   Coco    loro           Cacatúa     3         4
6   7   Nala   perro            Beagle     6         4
7   8  Simba    gato     Común Europeo     9         5
8   9   Bono   perro           Bulldog     2         5
9  10   Kira    gato            Angora     4         2>

### Ejercicio 4 — WHERE desde Python
 
No siempre necesitas traer toda la tabla. Filtrar en la consulta SQL antes de traer los datos es más eficiente que traer todo y filtrar después en Pandas — especialmente cuando la tabla tiene millones de filas.
 
**Consigna:** Escribe una consulta SQL con `WHERE` para traer solo los perros de la tabla `mascotas`. Sin bucles, sin filtros de Pandas después — el filtro va adentro de la consulta SQL.
 
Después muestra cuántos perros hay y qué razas aparecen.

In [16]:
import sqlite3
import pandas as pd
 
conexion = sqlite3.connect("vetcare.db")
 
df_perros = pd.read_sql(
    "SELECT * FROM mascotas WHERE especie = 'perro'",
    conexion
)
df_perros

   id nombre especie              raza  edad  dueno_id
0   1   Toby   perro          Labrador     4         1
1   3  Rocky   perro     Pastor Alemán     7         2
2   5    Max   perro  Golden Retriever     5         3
3   7   Nala   perro            Beagle     6         4
4   9   Bono   perro           Bulldog     2         5

> **Para pensar:** ¿cuál es la diferencia entre filtrar con `WHERE` en la consulta SQL y filtrar después de traer los datos con `pd.read_sql("SELECT * FROM mascotas", conexion)`? ¿Cuándo importa esa diferencia?

### Ejercicio 5 — Seleccionar columnas específicas
 
Traer `SELECT *` siempre trae todas las columnas, incluyendo las que no necesitás. En una tabla con 50 columnas, eso es mucho dato innecesario viajando por la red.
 
**Consigna:** Trae de la tabla `consultas` solo las columnas `fecha`, `motivo` y `costo`. Guardalo en un DataFrame y mostrá el costo máximo y mínimo de las consultas usando `max()` y `min()` de Pandas.

In [24]:
import sqlite3
import pandas as pd
 
conexion = sqlite3.connect("vetcare.db")
 
df_consultas = pd.read_sql(
    "SELECT fecha, motivo, costo FROM consultas",
    conexion
)
print(f'valor maximo : {max(df_consultas["costo"])}')
print(f'valor minimo : {min(df_consultas["costo"])}')
      
df_consultas

valor maximo : 45000.0
valor minimo : 2800.0

         fecha           motivo    costo
0   2024-03-01       vacunación   3500.0
1   2024-06-15    control anual   4200.0
2   2024-01-20   esterilización  18000.0
3   2024-02-10  cirugía rodilla  45000.0
4   2024-02-25  control post-op   3800.0
5   2024-04-05       vacunación   3200.0
6   2024-03-18    control anual   4200.0
7   2024-05-22  desparasitación   2800.0
8   2024-01-08  chequeo general   5500.0
9   2024-04-30    control anual   4200.0
10  2024-07-14       vacunación   3500.0
11  2024-02-28  chequeo general   4200.0
12  2024-05-10       vacunación   3500.0
13  2024-06-01    control anual   4200.0
14  2024-03-25   esterilización  15000.0

### Ejercicio 6 — LIMIT para explorar
 
Cuando empezás a trabajar con una tabla desconocida, pedirla completa es innecesario. Lo primero es ver cómo son los datos, no analizarlos todos.
 
**Consigna:** Trae solo las primeras 5 consultas de la tabla `consultas`, ordenadas por fecha de forma ascendente. Usá `ORDER BY` y `LIMIT` directamente en la consulta SQL.

In [26]:
import sqlite3
import pandas as pd
 
conexion = sqlite3.connect("vetcare.db")
 
df_primeras = pd.read_sql(
    "SELECT * FROM consultas ORDER BY fecha ASC LIMIT 5",
    conexion
)
 
print(df_primeras)

   id  mascota_id       fecha           motivo    costo  veterinario
0   9           6  2024-01-08  chequeo general   5500.0     Dr. Vera
1   3           2  2024-01-20   esterilización  18000.0    Dra. Sosa
2   4           3  2024-02-10  cirugía rodilla  45000.0     Dr. Vera
3   5           3  2024-02-25  control post-op   3800.0     Dr. Vera
4  12           8  2024-02-28  chequeo general   4200.0  Dra. Romero

### Ejercicio 7 — JOIN desde Python
 
La tabla `mascotas` tiene el `dueno_id`, pero no el nombre del dueño. Para verlos juntos necesitás unir las dos tablas, igual que hacías en SQLBolt.
 
**Consigna:** Escribe una consulta con `JOIN` para traer el nombre de la mascota, su especie y el nombre de su dueño, todo en un solo DataFrame. No uses dos `pd.read_sql()` separados y luego los combines — hacelo en una sola consulta SQL.

In [27]:
import sqlite3
import pandas as pd
 
conexion = sqlite3.connect("vetcare.db")
 
df_mascotas_duenos = pd.read_sql(
    "SELECT mascotas.nombre, mascotas.especie, duenos.nombre FROM mascotas INNER JOIN duenos ON mascotas.dueno_id = duenos.id",
    conexion
)
 
print(df_mascotas_duenos)

  nombre especie       nombre
0   Toby   perro   Ana Torres
1  Mishi    gato   Ana Torres
2  Rocky   perro   Luis Gómez
3   Luna    gato   Clara Díaz
4    Max   perro   Clara Díaz
5   Coco    loro   Pedro Ruiz
6   Nala   perro   Pedro Ruiz
7  Simba    gato  María López
8   Bono   perro  María López
9   Kira    gato   Luis Gómez

### Ejercicio 8 — Dos JOINs encadenados
 
Para ver el nombre del dueño junto con los datos de cada consulta médica, necesitas pasar por tres tablas: `consultas` → `mascotas` → `duenos`.
 
**Consigna:** Escribe una consulta que una las tres tablas y devuelva: nombre del dueño, nombre de la mascota, fecha de la consulta, motivo y costo. Ordená el resultado por fecha ascendente.

In [29]:
import sqlite3
import pandas as pd
 
conexion = sqlite3.connect("vetcare.db")
 
df_historial = pd.read_sql(
    "SELECT duenos.nombre, mascotas.nombre, consultas.fecha, consultas.motivo, consultas.costo FROM duenos INNER JOIN mascotas ON duenos.id = mascotas.dueno_id  INNER JOIN consultas ON consultas.mascota_id = mascotas.id ",conexion
)
 
print(df_historial)

         nombre nombre       fecha           motivo    costo
0    Ana Torres   Toby  2024-03-01       vacunación   3500.0
1    Ana Torres   Toby  2024-06-15    control anual   4200.0
2    Ana Torres  Mishi  2024-01-20   esterilización  18000.0
3    Luis Gómez  Rocky  2024-02-10  cirugía rodilla  45000.0
4    Luis Gómez  Rocky  2024-02-25  control post-op   3800.0
5    Clara Díaz   Luna  2024-04-05       vacunación   3200.0
6    Clara Díaz    Max  2024-03-18    control anual   4200.0
7    Clara Díaz    Max  2024-05-22  desparasitación   2800.0
8    Pedro Ruiz   Coco  2024-01-08  chequeo general   5500.0
9    Pedro Ruiz   Nala  2024-04-30    control anual   4200.0
10   Pedro Ruiz   Nala  2024-07-14       vacunación   3500.0
11  María López  Simba  2024-02-28  chequeo general   4200.0
12  María López   Bono  2024-05-10       vacunación   3500.0
13  María López   Bono  2024-06-01    control anual   4200.0
14   Luis Gómez   Kira  2024-03-25   esterilización  15000.0

> **Pista:** empeza desde la tabla `consultas` y hacé un `JOIN` con `mascotas`, y después otro `JOIN` con `duenos`. Cada `JOIN` necesita su propio `ON`.

### Ejercicio 9 — Investigación: alias en SQL
 
Cuando unes varias tablas, los nombres de las columnas pueden colisionar — dos tablas pueden tener una columna que se llama `id`, por ejemplo. Los alias resuelven ese problema.
 
**Consigna:** Investiga cómo usar `AS` en SQL para renombrar columnas y tablas en una consulta. Después reescribí la consulta del Ejercicio 8 usando alias para:
 
1. Renombrar `duenos.nombre` como `dueno` y `mascotas.nombre` como `mascota` en el resultado
2. Usar alias cortos para las tablas dentro de la consulta (por ejemplo, `c` para `consultas`, `m` para `mascotas`, `d` para `duenos`)

In [1]:
import sqlite3
import pandas as pd
 
conexion = sqlite3.connect("vetcare.db")
 
df_historial = pd.read_sql(
     "SELECT duenos.nombre AS 'dueno', mascotas.nombre AS 'mascota', consultas.fecha, consultas.motivo, consultas.costo FROM duenos INNER JOIN mascotas ON duenos.id = mascotas.dueno_id  INNER JOIN consultas ON consultas.mascota_id = mascotas.id ",conexion
    
)
 
print(df_historial.columns.tolist())
# Esperado: ['dueno', 'mascota', 'fecha', 'motivo', 'costo']

['dueno', 'mascota', 'fecha', 'motivo', 'costo']

### Ejercicio 10 — Filtrar después de unir
 
Necesitas ver el historial completo de consultas de una veterinaria, pero solo las que atendió la Dra. Sosa, junto con el nombre de la mascota.
 
**Consigna:** Escribe una consulta con `JOIN` y `WHERE` que devuelva el nombre de la mascota, la fecha, el motivo y el costo de todas las consultas atendidas por `'Dra. Sosa'`. Ordená por fecha descendente.

In [5]:
import sqlite3
import pandas as pd
 
conexion = sqlite3.connect("vetcare.db")
 
df_sosa = pd.read_sql(
    # Tu consulta acá
     "SELECT mascotas.nombre, consultas.fecha, consultas.motivo, consultas.costo, consultas.veterinario FROM mascotas INNER JOIN consultas ON consultas.mascota_id = mascotas.id  WHERE consultas.veterinario = 'Dra. Sosa' ORDER BY consultas.fecha ASC",conexion
    
)
 
print(df_sosa)
print(f"\nTotal facturado por Dra. Sosa: ${df_sosa['costo'].sum():,.0f}")

  nombre       fecha          motivo    costo veterinario
0  Mishi  2024-01-20  esterilización  18000.0   Dra. Sosa
1   Toby  2024-03-01      vacunación   3500.0   Dra. Sosa
2   Kira  2024-03-25  esterilización  15000.0   Dra. Sosa
3   Luna  2024-04-05      vacunación   3200.0   Dra. Sosa
4   Nala  2024-04-30   control anual   4200.0   Dra. Sosa
5   Nala  2024-07-14      vacunación   3500.0   Dra. Sosa

Total facturado por Dra. Sosa: $47,400

### Ejercicio 11 — El código que no cierra la conexión
 
Este código funciona, pero tiene un problema que en un script corto no se nota y en uno largo puede causar errores difíciles de rastrear.
 
**Consigna:** Ejecuta este código, identifica el problema, y reescribilo de forma correcta:

In [ ]:
import sqlite3
import pandas as pd

 
def obtener_mascotas(especie,conexion):
    
    df = pd.read_sql(
        f"SELECT * FROM mascotas WHERE especie = '{especie}'",
        conexion
    )
    return df


conexion = sqlite3.connect("vetcare.db") 
perros = obtener_mascotas("perro",conexion)
gatos = obtener_mascotas("gato",conexion)
loros = obtener_mascotas("loro",conexion)
conexion.close()
 
print(perros)
print(gatos)
print(loros)

   id nombre especie              raza  edad  dueno_id
0   1   Toby   perro          Labrador     4         1
1   3  Rocky   perro     Pastor Alemán     7         2
2   5    Max   perro  Golden Retriever     5         3
3   7   Nala   perro            Beagle     6         4
4   9   Bono   perro           Bulldog     2         5
   id nombre especie           raza  edad  dueno_id
0   2  Mishi    gato         Siamés     2         1
1   4   Luna    gato          Persa     1         3
2   8  Simba    gato  Común Europeo     9         5
3  10   Kira    gato         Angora     4         2
   id nombre especie     raza  edad  dueno_id
0   6   Coco    loro  Cacatúa     3         4

CORRECCION DE INYECTION SQL

In [ ]:
import sqlite3
import pandas as pd

 
def obtener_mascotas(especie,conexion):
    conexion = sqlite3.connect("vetcare.db")
    df = pd.read_sql(
        f"SELECT * FROM mascotas WHERE especie = '{especie}'",
        conexion
    )
    return df


pd.read_sql(
    "SELECT * FROM mascotas WHERE especie = ?",
    conexion,
    params=(especie,)  # la coma al final es necesaria: tiene que ser una tupla
)

conexion = sqlite3.connect("vetcare.db") 
perros = obtener_mascotas("perro",conexion)
gatos = obtener_mascotas("gato",conexion)
loros = obtener_mascotas("loro",conexion)
conexion.close()
 
print(perros)
print(gatos)
print(loros)

Hay dos problemas en este código. Uno ya lo mencionamos en el artículo. El otro es de seguridad — investigá qué es una **inyección SQL** y por qué el código de arriba es vulnerable.
 
> **Pista para el segundo problema:** busca "SQL injection" y "parámetros en sqlite3 Python". La solución involucra reemplazar el f-string por algo diferente.

### Ejercicio 12 — Consultas condicionales con Python
 
En un sistema real, las consultas que hacés no siempre son las mismas — cambian según lo que el usuario pide o el análisis que estás haciendo. Necesitás construir consultas dinámicamente desde Python.
 
**Consigna:** Escribe una función `buscar_mascotas(especie=None, edad_maxima=None, ciudad=None)` que construya y ejecute una consulta SQL según los parámetros que reciba. Si un parámetro es `None`, no se incluye en el filtro. La función debe devolver un DataFrame.

In [ ]:
import sqlite3
import pandas as pd
 
def buscar_mascotas(especie=None, edad_maxima=None, ciudad=None):
    conexion = sqlite3.connect("vetcare.db")
    
    # Tu tarea: construir la consulta dinámicamente
    # Si especie='perro', filtrar por especie
    # Si edad_maxima=5, filtrar mascotas con edad <= 5
    # Si ciudad='Buenos Aires', hacer JOIN con duenos y filtrar por ciudad
    # Si se pasan varios, combinar todos los filtros con AND
    
    pass
 
# Probar con distintas combinaciones:
print(buscar_mascotas(especie="perro"))
print(buscar_mascotas(edad_maxima=3))
print(buscar_mascotas(especie="gato", ciudad="Buenos Aires"))
print(buscar_mascotas())  # sin filtros → devuelve todas

### Ejercicio 13 — Reporte por veterinario
 
La clínica quiere saber cuánto facturó cada veterinario y cuántas consultas atendió. En la próxima clase vas a aprender `GROUP BY` y funciones de agregación en SQL — por ahora, hacelo con las herramientas que ya conocés.
 
**Consigna:** Trae todas las consultas con `pd.read_sql()` y calculá manualmente, usando Python puro (sin `.groupby()` ni `.mean()`), cuántas consultas atendió cada veterinario y cuánto facturó en total. Generá un reporte formateado.

In [ ]:
import sqlite3
import pandas as pd
 
conexion = sqlite3.connect("vetcare.db")
 
df = pd.read_sql("SELECT veterinario, costo FROM consultas", conexion)
conexion.close()
 
# Tu tarea: sin groupby() ni mean(), calcular por veterinario:
# - cantidad de consultas
# - total facturado
# Pista: podés usar df["veterinario"].unique() para obtener los
# veterinarios únicos, y df[df["veterinario"] == nombre] para filtrar

> **Para pensar:** este ejercicio te muestra por qué `GROUP BY` existe. Anotá cuántas líneas necesitaste. En la próxima clase vas a resolver lo mismo en dos líneas con SQL.

### Ejercicio 14 — Múltiples consultas, una conexión
 
Abrir y cerrar una conexión para cada consulta es innecesario y lento. En un análisis real, usás una sola conexión para todas las consultas que necesitás en ese script.
 
**Consigna:** Usando una sola conexión a `vetcare.db`, ejecutá estas cuatro consultas y generá un reporte completo de la clínica:
 
1. Total de dueños registrados
2. Distribución de mascotas por especie (cuántos perros, gatos, etc.)
3. La consulta más cara y la más barata
4. Las mascotas que nunca tuvieron una consulta (están en `mascotas` pero no en `consultas`)

In [ ]:
import sqlite3
import pandas as pd
 
conexion = sqlite3.connect("vetcare.db")
 
# Haz las cuatro consultas usando la misma conexión
# Para el punto 4: investiga LEFT JOIN e IS NULL
# (lo viste en SQLBolt Lección 7 y 8)
 
conexion.close()

→ [Ver solución](./solucion.md) *(intenta primero)*